#!/bin/sh

case "$1" in
	start)
		# Load PWM driver
		modprobe pwm-bcm2835
		
		# Load WiFi driver
		modprobe brcmfmac
		
		# Load MCP3002 all needed SPI drivers
		modprobe spi-bcm2835
		modprobe spidev
		modprobe mcp320x
		
		# Create /dev/video device to make OpenCV detect the camera
		modprobe bcm2835-v4l2
		modprobe bcm2835_codec
		;;

	stop)
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
