name: Buildroot build
on: [push]

jobs:
  buildroot_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'
