name: Buildroot build
on: [push]

jobs:
  buildroot_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Buildroot distribution build
        run: |
          make -C Software/Raspberry_Pi/buildroot BR2_EXTERNAL=$(realpath ..)/cyclope cyclope_defconfig
          make -C Software/Raspberry_Pi/buildroot
