name: PC application build
on: [push]

env:
    QT_VERSION: '5.14.2'

jobs:
  pc_application_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{env.QT_VERSION}}
